name: Acoustic Theology
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: where being given meets understanding
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020003'
    - '#a41911'
    - '#00f4f9'
    - '#fbfcfe'
    - '#fb6533'
  brandStrength: 0.3456435075495392
  lightness: 0.9803922295104712
  saturation: 0.2959469754714519
  rhythmicContrast: 0.1438960509840399
purpose: []
