name: Acoustic Theology
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: where being given meets understanding
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff341c'
    - '#330201'
    - '#ff6e28'
    - '#fdf952'
    - '#fdfddd'
  brandStrength: 0.3456435075495392
  lightness: 0.9803922295104712
  saturation: 0.2959469754714519
  rhythmicContrast: 0.1438960509840399
purpose: []
