name: Acoustic Theology
favicon: null
layout_spectrum: 0.27278
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3456435075495392
  lightness: 0.9803922295104712
  saturation: 0.2959469754714519
  rhythmicContrast: 0.1438960509840399
purpose: []
