name: Acoustic Theology
favicon: null
layout_spectrum: 0.49463
typography_spectrum: 0.75805
title: 'Acoustic Theology: where being given seeks understanding'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020003'
    - '#a41911'
    - '#00f4f9'
    - '#fbfcfe'
    - '#fb6533'
  brandStrength: 0.1875
  lightness: 0.0625
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
